@startuml packages_citegres
set namespaceSeparator none
top to bottom direction
skinparam componentStyle rectangle
rectangle "guitility\n1 python file" as guitility
rectangle "netility\n1 python file" as netility
rectangle "nordility\n1 python file" as nordility
rectangle "postility\n1 python file" as postility
rectangle "seleamility\n1 python file" as seleamility
guitility --> netility
guitility --> nordility
guitility --> postility
guitility --> seleamility
seleamility --> nordility
@enduml
